#
# This file defines the services that make up the application
# Each service is a container that runs a single process
# Each container is built from an image, according to the Dockerfile specified in the build section
# For more information, see: https://docs.docker.com/compose/compose-file/
#

services:
  web:  # Define the web service
    build:  # Define how to build the Docker image
      context: .  # Directory containing the Dockerfile
      dockerfile: Dockerfile  # Specify the Dockerfile (optional if named Dockerfile)
    ports:  # Specify port mappings
      - "8002:80"  # Map port 8002 on the host to port 8001 in the container
    volumes:  # Define volume mounts
      - ".:/var/www/html"  # Mount the local ./src directory to /var/www/html in the container
    restart: always  # Always restart the container if it stops